7zip/7z1604-x64.msi:
  size: 1668096
  object_id: bedc5852-10af-44ee-6899-40a6d24283d7
  sha: bae316e5148d3b42efa1d3f272afc10d3ffa6f4b
bosh-cli/bosh-cli-2.0.40-windows-amd64.exe:
  size: 27397632
  object_id: 80961a4c-7921-4c24-77e1-71ae9ee5ccc5
  sha: fffd495e33258dd68bd8b7f92f3d09f25e68f4a4
cmake/cmake-3.8.0-rc2-win64-x64.zip:
  size: 25615806
  object_id: 723cc335-e647-46bf-631a-d81135fdcb3d
  sha: dd65bc4af74bb019056dc2d9dcaa4d079f3a0abd
docker/docker-17.06.0-dev.zip:
  size: 17748489
  object_id: a1ce85f2-8c6a-4f2f-5bf1-cb3abb2c90a1
  sha: c21469c707a7362de8766582b7a28dbb4194e8df
git/Git-2.13.0-64-bit.exe:
  size: 37156256
  object_id: f5373af5-252d-41ff-63c1-a2f60ad1846e
  sha: e1d7c6e5e16acaf3c108064a2ed158f604fa29a7
golang/go1.10.3.windows-amd64.zip:
  size: 139354339
  object_id: aaa309e6-6495-4696-4e04-e1d1776ae5d4
  sha: bc3500c018b4265f13913e5cb83cc0ac84334779
make-dep/make-3.81-dep.zip:
  size: 708206
  object_id: 5b796c1a-c554-4ef9-6296-d13053e08024
  sha: ee90e45c1bacc24a0c3852a95fc6dcfbcabe802b
make/make-3.81-bin.zip:
  size: 495645
  object_id: 4dc3c974-bd26-482e-74ed-dfe774444320
  sha: 7c1e23a93e6cb78975f36efd22d598241b1f0e8b
mingw/i686-7.2.0-release-win32-dwarf-rt_v5-rev0.7z:
  size: 44128425
  object_id: 7abf9665-2e74-4a1d-4b8f-aa090660e60e
  sha: 4be200a4aa1cb0fab2a40915767321e047b8c043
mingw/x86_64-7.2.0-release-posix-seh-rt_v5-rev0.7z:
  size: 48975566
  object_id: 9eda914e-e920-434b-4535-f2c397497817
  sha: 5e4ca4485384f04399ae0aa06bab509721c50095
processhacker/processhacker-2.39-bin.zip:
  size: 3392412
  object_id: 52e8388f-8ea2-4a7e-5a38-acc1982023d3
  sha: 8e8f8423d163d922242b8b7d85427664f77edc97
ruby/ruby-2.3.3-x64.exe:
  size: 19668866
  object_id: 331c4055-4638-4076-5e25-4c22217c5c55
  sha: 83ae5e6282a2b7e21bb61c5b4d1b184c33edbd2a
